image: node

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - cp build/index.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main