image: node


before_script:
  - rm -rf build
  - CI=false npm install

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
   env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_PROXY_URL: ${{ secrets.REACT_APP_PROXY_URL }}

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
